name: Build and Upload Static Site

on:
  workflow_dispatch:
  push:
    branches:
#      - main
      - new-site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Debug List .gitmodules file
        run: ls -la .gitmodules || echo ".gitmodules not found"

      - name: Remove lingering .gitmodules file
        run: rm -f .gitmodules

      - name: Checkout page-scribe-static-flow repository
        uses: actions/checkout@v4
        with:
          repository: as-a-discipline/page-scribe-static-flow
          path: _website/page-scribe-static-flow
          token: ${{ secrets.GH_PAT }}
          ref: main

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build.sh
        run: ./build.sh

      - name: Remove symlinks and hard links from build output
        run: |
          find _website/page-scribe-static-flow/dist -type l -delete
          # Remove hard links (uncommon, but for completeness)
          find _website/page-scribe-static-flow/dist -type f -links +1 -exec rm {} \;

      - name: Remove symlinks and hard links from build output
        run: |
          mkdir -p _website/page-scribe-static-flow/dist/assets/src
          mkdir -p _website/page-scribe-static-flow/dist/assets/src/assets
          cp -R ./_website/page-scribe-static-flow/src/assets ./_website/page-scribe-static-flow/dist/assets/
          cp -R ./_website/page-scribe-static-flow/src/assets ./_website/page-scribe-static-flow/dist/assets/src/assets


      - name: Remove symlinks and hard links from build output
        run: |
          chmod -R a+rX _website/page-scribe-static-flow/dist

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: _website/page-scribe-static-flow/dist


  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4